apiVersion: v1
kind: List
items:
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedDeployment
  metadata:
    labels:
      name: mongo
    name: mongo
  spec:
    template:
      metadata:
        labels:
          name: mongo
      spec:
        replicas: 0
        selector:
          matchLabels:
            name: mongo
        template:
          metadata:
            labels:
              name: mongo
          spec:
            containers:
            - image: mongo
              name: mongo
              ports:
              - name: mongo
                containerPort: 27017
              args:
              - --replSet
              - rs0
              volumeMounts:
                - name: mongo-db
                  mountPath: /data/db
            volumes:
              - name: mongo-db
                persistentVolumeClaim:
                  claimName: mongodata
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedDeploymentPlacement
  metadata:
    name: mongo
  spec:
    clusterNames:
    - "null"
