apiVersion: v1
kind: List
items:
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedDeployment
  metadata:
    labels:
      name: pacman
    name: pacman
  spec:
    template:
      metadata:
        labels:
          name: pacman
      spec:
        replicas: 0
        selector:
          matchLabels:
            name: pacman
        template:
          metadata:
            labels:
              name: pacman
          spec:
            containers:
            - image: quay.io/ifont/pacman-nodejs-app:v1.0.3
              name: pacman
              imagePullPolicy: Always
              env:
              - name: MONGO_REPLICA_SET
                value: rs0
              - name: MONGO_NAMESPACE_SERVICE_HOST
                value: mongo.mongo.svc.cluster.local
              - name: NUM_HIGHSCORE
                value: "100"
              ports:
              - containerPort: 8080
                name: http-server
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedDeploymentOverride
  metadata:
    name: pacman
  spec:
    overrides:
    - clusterName: aws-us-east1
      clusterOverrides:
      - path: spec.replicas
        value: 3
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedDeploymentPlacement
  metadata:
    name: pacman
  spec:
    clusterNames:
    - "null"
