kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gluster-pvc-mongolog
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: gluster-storage
