apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-mongolog
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gluster-storage
