apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.0.0.1
    ports:
      - port: 1
  - addresses:
      - ip: 10.0.1.1
    ports:
      - port: 1
  - addresses:
      - ip: 10.0.2.1
    ports:
      - port: 1
